import type { FieldDef } from "./schemaTypes";

/** Verification, Safety, Notifications, Misc. */
export const FIELDS_D: readonly FieldDef[] = [
  // ---- Verification ----
  {
    group: "verification",
    key: "autoVerify",
    kind: "dropdown",
    name: "Check each new backup",
    desc: "L1 reads the structure, L2 also checks CRCs, L3 also checks every file's SHA-256. Higher is slower.",
    options: [
      { value: "off", label: "Off" },
      { value: "L1", label: "L1 structure" },
      { value: "L2", label: "L2 + CRC" },
      { value: "L3", label: "L3 + SHA-256" },
    ],
  },
  {
    group: "verification",
    key: "samplingPct",
    kind: "number",
    name: "Sampling check size",
    desc: "The 'sampling verify' check reads this percentage of randomly chosen files.",
    min: 1,
    max: 100,
    unit: "%",
  },
  {
    group: "verification",
    key: "scheduledDeepVerify",
    kind: "toggle",
    name: "Run a deep check regularly",
    desc: "Checks that the newest backup and everything it depends on is intact.",
  },
  {
    group: "verification",
    key: "deepVerifyIntervalDays",
    kind: "number",
    name: "Deep check interval",
    desc: "Days between deep checks.",
    min: 1,
    max: 365,
    unit: "days",
    shownIf: { key: "scheduledDeepVerify", value: true },
  },
  {
    group: "verification",
    key: "onFailureForceFull",
    kind: "toggle",
    name: "Make a full backup after a failed check",
    desc: "Recommended. Turned off, later differential backups stack on a damaged one and cannot be restored.",
  },
  {
    group: "verification",
    key: "onFailureNotify",
    kind: "toggle",
    name: "Show a message when a check fails",
    desc: "Also respects the notification level below.",
  },

  // ---- Safety ----
  {
    group: "safety",
    key: "massChangeGuard",
    kind: "toggle",
    name: "Mass-change guard",
    desc: "Pause automatic backups when very many files change at once (a bad sync, plugin or ransomware), so the last good backup is protected.",
  },
  {
    group: "safety",
    key: "massChangeThreshold",
    kind: "number",
    name: "Mass-change threshold",
    desc: "Number of changed files that counts as a mass change.",
    min: 1,
    max: 1_000_000,
    unit: "files",
    shownIf: { key: "massChangeGuard", value: true },
  },
  {
    group: "safety",
    key: "massChangeWindowSec",
    kind: "number",
    name: "Mass-change window",
    desc: "The time span in which that many changes count.",
    min: 1,
    max: 86_400,
    unit: "seconds",
    shownIf: { key: "massChangeGuard", value: true },
  },
  {
    group: "safety",
    key: "preRestoreSnapshot",
    kind: "toggle",
    name: "Snapshot before restoring into the vault",
    desc: "Recommended. Takes a backup of the current vault first so a restore can be undone.",
  },
  {
    group: "safety",
    key: "preRiskSnapshots",
    kind: "toggle",
    name: "Snapshot before risky changes",
    desc: "Before plugin updates and bulk deletes or renames.",
  },
  {
    group: "safety",
    key: "lockTimeoutMin",
    kind: "number",
    name: "Lock timeout",
    desc: "A backup that has not reported progress for this long is considered crashed and its lock is released.",
    min: 1,
    max: 1440,
    unit: "minutes",
  },

  // ---- Notifications ----
  {
    group: "notifications",
    key: "level",
    kind: "dropdown",
    name: "Notification level",
    desc: "Everything is always written to the log file.",
    options: [
      { value: "silent", label: "Silent" },
      { value: "errors", label: "Errors only" },
      { value: "verbose", label: "Verbose" },
    ],
  },
  {
    group: "notifications",
    key: "dailyNoteFailureAppend",
    kind: "toggle",
    name: "Add backup failures to the daily note",
    desc: "So a failure is not missed.",
  },
  {
    group: "notifications",
    key: "dailyNotePath",
    kind: "text",
    name: "Daily note to append to",
    desc: "Vault-relative path of the note, e.g. Journal/Backup alerts.md",
    placeholder: "Journal/Backup alerts.md",
    shownIf: { key: "dailyNoteFailureAppend", value: true },
  },
  {
    group: "notifications",
    key: "statusBar",
    kind: "toggle",
    name: "Show backup status in the status bar",
    desc: "Desktop only.",
    desktopOnly: true,
  },
  {
    group: "notifications",
    key: "logSizeCapKb",
    kind: "number",
    name: "Log size limit",
    desc: "The log file is rotated when it reaches this size.",
    min: 16,
    max: 102_400,
    unit: "KB",
  },

  // ---- Misc ----
  {
    group: "misc",
    key: "settingsPassphraseEnabled",
    kind: "toggle",
    name: "Protect copied settings with a passphrase",
    desc: '"Copy settings as a link" then asks for a passphrase and encrypts the link, so it is safe to send. Your backup passphrase is never included.',
  },
  {
    group: "misc",
    key: "lowMemoryMode",
    kind: "toggle",
    name: "Low-memory mode",
    desc: "Smaller chunks, for phones that run out of memory on big vaults.",
  },
  {
    group: "misc",
    key: "chunkSizeKb",
    kind: "number",
    name: "Chunk size",
    desc: "How much data is processed before the app gets a chance to redraw. Smaller is smoother but slower.",
    min: 16,
    max: 16_384,
    unit: "KB",
  },
];
