import type { FieldDef } from "./schemaTypes";

/** Triggers, Conditions, Exclusions. */
export const FIELDS_C: readonly FieldDef[] = [
  // ---- Triggers ----
  {
    group: "triggers",
    key: "onResume",
    kind: "toggle",
    name: "Back up when Obsidian returns to the foreground",
    desc: "Useful on phones, where Obsidian is paused in the background.",
  },
  {
    group: "triggers",
    key: "resumeMinGapMin",
    kind: "number",
    name: "Minimum time between resume backups",
    desc: "A resume backup is skipped if a backup was made more recently than this.",
    min: 0,
    max: 10_080,
    unit: "minutes",
    shownIf: { key: "onResume", value: true },
  },
  {
    group: "triggers",
    key: "intervalEnabled",
    kind: "toggle",
    name: "Back up on a timer",
    desc: "Only while Obsidian is open and in the foreground (on phones).",
  },
  {
    group: "triggers",
    key: "intervalMinutes",
    kind: "number",
    name: "Timer interval",
    desc: "Minutes between timed backups.",
    min: 1,
    max: 10_080,
    unit: "minutes",
    shownIf: { key: "intervalEnabled", value: true },
  },
  {
    group: "triggers",
    key: "dailyTimes",
    kind: "list",
    name: "Daily backup times",
    desc: "One time per line, 24 hour HH:MM, in local time. Needs Obsidian to be open at that time.",
    placeholder: "09:00\n18:30",
    validate: "time",
  },
  {
    group: "triggers",
    key: "afterEditsEnabled",
    kind: "toggle",
    name: "Back up after a number of edits",
    desc: "Counts edited notes, not keystrokes.",
  },
  {
    group: "triggers",
    key: "afterEdits",
    kind: "number",
    name: "Number of edits",
    desc: "Back up once this many edits have happened since the last backup.",
    min: 1,
    max: 100_000,
    shownIf: { key: "afterEditsEnabled", value: true },
  },
  {
    group: "triggers",
    key: "afterWordsEnabled",
    kind: "toggle",
    name: "Back up after a number of words",
    desc: "Counts how many words you added or removed in notes. A good fit for long writing sessions in a few big notes.",
  },
  {
    group: "triggers",
    key: "afterWords",
    kind: "number",
    name: "Number of words",
    desc: "Back up once this many words have changed since the last backup.",
    min: 10,
    max: 1_000_000,
    unit: "words",
    shownIf: { key: "afterWordsEnabled", value: true },
  },
  {
    group: "triggers",
    key: "idleEnabled",
    kind: "toggle",
    name: "Back up when idle",
    desc: "After you stop editing for a while.",
  },
  {
    group: "triggers",
    key: "idleMinutes",
    kind: "number",
    name: "Idle time",
    desc: "Minutes without edits before the idle backup.",
    min: 1,
    max: 1440,
    unit: "minutes",
    shownIf: { key: "idleEnabled", value: true },
  },
  {
    group: "triggers",
    key: "onCreate",
    kind: "toggle",
    name: "Back up after files are created",
    desc: "Waits for a short quiet period, so creating many files makes one backup.",
  },
  {
    group: "triggers",
    key: "onDelete",
    kind: "toggle",
    name: "Back up after files are deleted",
    desc: "Waits for a short quiet period, so deleting many files makes one backup.",
  },
  {
    group: "triggers",
    key: "onRename",
    kind: "toggle",
    name: "Back up after files are renamed or moved",
    desc: "Waits for a short quiet period, so a bulk rename makes one backup.",
  },
  {
    group: "triggers",
    key: "onClose",
    kind: "toggle",
    name: "Back up when Obsidian closes",
    desc: "Best effort: Obsidian may quit before the backup finishes. Desktop only.",
    desktopOnly: true,
  },

  // ---- Conditions ----
  {
    group: "conditions",
    key: "minBatteryPct",
    kind: "number",
    name: "Minimum battery level",
    desc: "Automatic backups wait while the battery is below this and not charging. 0 turns this off.",
    min: 0,
    max: 100,
    unit: "%",
  },
  {
    group: "conditions",
    key: "skipIfNoChanges",
    kind: "toggle",
    name: "Skip when nothing changed",
    desc: "Do not make a new backup if no file has changed since the last one.",
  },
  {
    group: "conditions",
    key: "minFreeSpaceMb",
    kind: "number",
    name: "Minimum free space",
    desc: "Refuse to back up if less than this would be left. Where free space cannot be measured the check is skipped.",
    min: 0,
    max: 1_000_000,
    unit: "MB",
  },
  {
    group: "conditions",
    key: "wifiOnly",
    kind: "toggle",
    name: "Only on Wi-Fi or wired networks",
    desc: "For vaults that sync: avoid mobile data. Where the connection type is unknown the backup still runs.",
  },

  // ---- Exclusions ----
  {
    group: "exclusions",
    key: "globs",
    kind: "list",
    name: "Excluded paths",
    desc: "One pattern per line, gitignore style: *.tmp, attachments/, !keep/this.md",
    placeholder: "*.tmp\nattachments/",
  },
  {
    group: "exclusions",
    key: "excludeHidden",
    kind: "toggle",
    name: "Exclude hidden files and folders",
    desc: "Overrides Basic > Include hidden.",
  },
  {
    group: "exclusions",
    key: "excludeObsidian",
    kind: "toggle",
    name: "Exclude the .obsidian folder",
    desc: "Your settings, themes and plugins. Backing it up lets you restore your setup too.",
  },
  {
    group: "exclusions",
    key: "excludeGit",
    kind: "toggle",
    name: "Exclude .git folders",
    desc: "Version-control data, usually large and already stored elsewhere.",
  },
  {
    group: "exclusions",
    key: "excludeNodeModules",
    kind: "toggle",
    name: "Exclude node_modules folders",
    desc: "Rebuildable dependencies.",
  },
  {
    group: "exclusions",
    key: "excludeTrash",
    kind: "toggle",
    name: "Exclude the .trash folder",
    desc: "Notes you deleted inside Obsidian.",
  },
];
