import { ENCRYPTION } from "../constants";
import type { FieldDef } from "./schemaTypes";

/** Retention, Encryption. */
export const FIELDS_B: readonly FieldDef[] = [
  // ---- Retention ----
  {
    group: "retention",
    key: "keepLast",
    kind: "number",
    name: "Keep the newest backups",
    desc: "Older ones are deleted after each backup. The newest intact backup is never deleted. With differential backups, older backups that newer ones depend on are kept too, so more than this many may remain until the next full backup.",
    min: 1,
    max: 100_000,
  },
  {
    group: "retention",
    key: "keepDays",
    kind: "number",
    name: "Also keep backups from the last",
    desc: "Backups younger than this are kept even if they exceed the number above. 0 turns this off.",
    min: 0,
    max: 36_500,
    unit: "days",
  },
  {
    group: "retention",
    key: "gfsEnabled",
    kind: "toggle",
    name: "Keep daily, weekly and monthly backups",
    desc: "Also keeps the newest backup of each recent day, week and month (UTC).",
  },
  {
    group: "retention",
    key: "gfsDaily",
    kind: "number",
    name: "Daily backups to keep",
    desc: "Number of recent days that have a backup.",
    min: 0,
    max: 3650,
    shownIf: { key: "gfsEnabled", value: true },
  },
  {
    group: "retention",
    key: "gfsWeekly",
    kind: "number",
    name: "Weekly backups to keep",
    desc: "Number of recent weeks that have a backup (weeks start on Monday).",
    min: 0,
    max: 520,
    shownIf: { key: "gfsEnabled", value: true },
  },
  {
    group: "retention",
    key: "gfsMonthly",
    kind: "number",
    name: "Monthly backups to keep",
    desc: "Number of recent months that have a backup.",
    min: 0,
    max: 240,
    shownIf: { key: "gfsEnabled", value: true },
  },
  {
    group: "retention",
    key: "maxFolderMb",
    kind: "number",
    name: "Maximum backup folder size",
    desc: "Delete the oldest backups until the folder fits. Never deletes the newest intact backup or pinned ones, so it may stay over the limit. 0 means no limit.",
    min: 0,
    max: 10_000_000,
    unit: "MB",
  },
  {
    group: "retention",
    key: "pinnedExempt",
    kind: "toggle",
    name: "Never delete pinned backups",
    desc: "Pinned milestones are exempt from every retention rule.",
  },

  // ---- Encryption ----
  {
    group: "encryption",
    key: "enabled",
    kind: "toggle",
    name: "Encrypt backups",
    desc: "AES-256-GCM. If you lose the passphrase the backups cannot be recovered; there is no reset. File names stay readable inside the ZIP.",
  },
  {
    group: "encryption",
    key: "sessionCache",
    kind: "toggle",
    name: "Remember the passphrase until Obsidian closes",
    desc: "Ask once per session instead of on every backup.",
    shownIf: { key: "enabled", value: true },
  },
  {
    group: "encryption",
    key: "promptOnDemand",
    kind: "toggle",
    name: "Ask for the passphrase when needed",
    desc: "Show a prompt when a backup or restore needs it and none is stored.",
    shownIf: { key: "enabled", value: true },
  },
  {
    group: "encryption",
    key: "passphrase",
    kind: "password",
    name: "Stored passphrase",
    desc: "Optional. Saved in this plugin's data.json in plain text, readable by anyone with the vault. Leave empty to be asked instead.",
    shownIf: { key: "enabled", value: true },
  },
  {
    group: "encryption",
    key: "kdfIterations",
    kind: "number",
    name: "Key derivation iterations",
    desc: "PBKDF2-SHA256 work factor. Higher is slower for attackers and for you. Cannot go below the minimum.",
    min: ENCRYPTION.minIterations,
    max: 100_000_000,
    shownIf: { key: "enabled", value: true },
  },
];
